{{
  config(
    materialized='table',
    schema=env_var('BQ_MARTS_FINANCIAL_DATASET', 'mobius_financial_dev'),
    tags=['periodic'],
    enabled=var('run_periodic', false),
  )
}}

-- Organization-to-organization peer distribution statistics — v2.
-- Uses credentialing-deduped org identity (org_kpis_v2 / org_slug, 1,474 orgs).
-- One row per org_type × peer_group × size_band × market_tier × geo_level × geo_id × period_year.
--
-- peer_group encodes which stratification filters are applied:
--   'type_only'          — org_type match only (widest, highest n)
--   'type_size'          — org_type + size_band
--   'type_market'        — org_type + market_tier
--   'type_size_market'   — org_type + size_band + market_tier (tightest, most comparable)
--
-- The API selects the tightest peer_group with n >= 3, falling back toward wider groups.
-- size_band / market_tier are populated only when they are part of the filter; NULL otherwise.
--
-- KPI distributions: panel_per_clinician, servicing_npi_count, claims_per_bene, payment_per_claim.
-- Mix distributions: avg psychiatry_pct, counselor_pct, social_worker_pct, mft_pct,
--                    psychologist_pct, aprn_pct — explain WHY payment_per_claim differs.
--
-- Geo levels: national ('US'), state, zip. Minimum n = 3.

with base as (
    select
        k.org_slug,
        k.period_year,
        k.org_type,
        k.market_tier,
        k.size_band,
        k.org_state,
        k.org_zip5,
        k.panel_per_clinician,
        k.servicing_npi_count,
        k.claims_per_beneficiary,
        k.payment_per_claim,
        k.psychiatry_pct,
        k.counselor_pct,
        k.social_worker_pct,
        k.mft_pct,
        k.psychologist_pct,
        k.aprn_pct,
        k.market_share_pct,
        k.intake_market_share,
        k.high_acuity_market_share,
        k.ongoing_market_share,
        k.intake_revenue_pct,
        k.high_acuity_revenue_pct,
        k.ongoing_revenue_pct,
        k.intake_bene_pct,
        k.high_acuity_bene_pct,
        k.ongoing_bene_pct
    from {{ ref('org_kpis_v2') }} k
    where k.panel_per_clinician    is not null
      and k.panel_per_clinician    >  0
      and k.claims_per_beneficiary is not null
      and k.payment_per_claim      is not null
),

-- ── type_only — widest cut, org_type match only ───────────────────────────────

to_national as (
    select org_type, 'type_only' as peer_group,
        cast(null as string) as size_band, cast(null as string) as market_tier,
        'national' as geo_level, 'US' as geo_id, period_year,
        count(distinct org_slug)                              as n,
        avg(panel_per_clinician)                                   as mean_panel_per_clin,
        approx_quantiles(panel_per_clinician, 4)[offset(1)]       as p25_panel_per_clin,
        approx_quantiles(panel_per_clinician, 4)[offset(2)]       as p50_panel_per_clin,
        approx_quantiles(panel_per_clinician, 4)[offset(3)]       as p75_panel_per_clin,
        stddev(panel_per_clinician)                                as std_panel_per_clin,
        avg(cast(servicing_npi_count as float64))                  as mean_clinician_count,
        approx_quantiles(servicing_npi_count, 4)[offset(1)]       as p25_clinician_count,
        approx_quantiles(servicing_npi_count, 4)[offset(2)]       as p50_clinician_count,
        approx_quantiles(servicing_npi_count, 4)[offset(3)]       as p75_clinician_count,
        avg(claims_per_beneficiary)                                as mean_claims_per_bene,
        approx_quantiles(claims_per_beneficiary, 4)[offset(1)]    as p25_claims_per_bene,
        approx_quantiles(claims_per_beneficiary, 4)[offset(2)]    as p50_claims_per_bene,
        approx_quantiles(claims_per_beneficiary, 4)[offset(3)]    as p75_claims_per_bene,
        stddev(claims_per_beneficiary)                             as std_claims_per_bene,
        avg(payment_per_claim)                                     as mean_payment_per_claim,
        approx_quantiles(payment_per_claim, 4)[offset(1)]         as p25_payment_per_claim,
        approx_quantiles(payment_per_claim, 4)[offset(2)]         as p50_payment_per_claim,
        approx_quantiles(payment_per_claim, 4)[offset(3)]         as p75_payment_per_claim,
        stddev(payment_per_claim)                                  as std_payment_per_claim,
        avg(psychiatry_pct)    as avg_psychiatry_pct,
        avg(counselor_pct)     as avg_counselor_pct,
        avg(social_worker_pct) as avg_social_worker_pct,
        avg(mft_pct)           as avg_mft_pct,
        avg(psychologist_pct)  as avg_psychologist_pct,
        avg(aprn_pct)          as avg_aprn_pct,
        avg(market_share_pct)                                      as mean_market_share,
        approx_quantiles(market_share_pct, 4)[offset(1)]           as p25_market_share,
        approx_quantiles(market_share_pct, 4)[offset(2)]           as p50_market_share,
        approx_quantiles(market_share_pct, 4)[offset(3)]           as p75_market_share,
        avg(intake_market_share)                                    as mean_intake_market_share,
        approx_quantiles(intake_market_share, 4)[offset(1)]        as p25_intake_market_share,
        approx_quantiles(intake_market_share, 4)[offset(2)]        as p50_intake_market_share,
        approx_quantiles(intake_market_share, 4)[offset(3)]        as p75_intake_market_share,
        avg(high_acuity_market_share)                               as mean_high_acuity_market_share,
        approx_quantiles(high_acuity_market_share, 4)[offset(1)]   as p25_high_acuity_market_share,
        approx_quantiles(high_acuity_market_share, 4)[offset(2)]   as p50_high_acuity_market_share,
        approx_quantiles(high_acuity_market_share, 4)[offset(3)]   as p75_high_acuity_market_share,
        avg(ongoing_market_share)                                   as mean_ongoing_market_share,
        approx_quantiles(ongoing_market_share, 4)[offset(1)]       as p25_ongoing_market_share,
        approx_quantiles(ongoing_market_share, 4)[offset(2)]       as p50_ongoing_market_share,
        approx_quantiles(ongoing_market_share, 4)[offset(3)]       as p75_ongoing_market_share,
        avg(intake_revenue_pct)                                     as mean_intake_revenue_pct,
        approx_quantiles(intake_revenue_pct, 4)[offset(1)]         as p25_intake_revenue_pct,
        approx_quantiles(intake_revenue_pct, 4)[offset(2)]         as p50_intake_revenue_pct,
        approx_quantiles(intake_revenue_pct, 4)[offset(3)]         as p75_intake_revenue_pct,
        avg(high_acuity_revenue_pct)                                as mean_high_acuity_revenue_pct,
        approx_quantiles(high_acuity_revenue_pct, 4)[offset(1)]    as p25_high_acuity_revenue_pct,
        approx_quantiles(high_acuity_revenue_pct, 4)[offset(2)]    as p50_high_acuity_revenue_pct,
        approx_quantiles(high_acuity_revenue_pct, 4)[offset(3)]    as p75_high_acuity_revenue_pct,
        avg(ongoing_revenue_pct)                                    as mean_ongoing_revenue_pct,
        approx_quantiles(ongoing_revenue_pct, 4)[offset(1)]        as p25_ongoing_revenue_pct,
        approx_quantiles(ongoing_revenue_pct, 4)[offset(2)]        as p50_ongoing_revenue_pct,
        approx_quantiles(ongoing_revenue_pct, 4)[offset(3)]        as p75_ongoing_revenue_pct,
        avg(intake_bene_pct)                                        as mean_intake_bene_pct,
        approx_quantiles(intake_bene_pct, 4)[offset(1)]            as p25_intake_bene_pct,
        approx_quantiles(intake_bene_pct, 4)[offset(2)]            as p50_intake_bene_pct,
        approx_quantiles(intake_bene_pct, 4)[offset(3)]            as p75_intake_bene_pct,
        avg(high_acuity_bene_pct)                                   as mean_high_acuity_bene_pct,
        approx_quantiles(high_acuity_bene_pct, 4)[offset(1)]       as p25_high_acuity_bene_pct,
        approx_quantiles(high_acuity_bene_pct, 4)[offset(2)]       as p50_high_acuity_bene_pct,
        approx_quantiles(high_acuity_bene_pct, 4)[offset(3)]       as p75_high_acuity_bene_pct,
        avg(ongoing_bene_pct)                                       as mean_ongoing_bene_pct,
        approx_quantiles(ongoing_bene_pct, 4)[offset(1)]           as p25_ongoing_bene_pct,
        approx_quantiles(ongoing_bene_pct, 4)[offset(2)]           as p50_ongoing_bene_pct,
        approx_quantiles(ongoing_bene_pct, 4)[offset(3)]           as p75_ongoing_bene_pct
    from base
    group by org_type, peer_group, size_band, market_tier, geo_level, geo_id, period_year
    having count(distinct org_slug) >= 3
),

to_state as (
    select org_type, 'type_only' as peer_group,
        cast(null as string) as size_band, cast(null as string) as market_tier,
        'state' as geo_level, org_state as geo_id, period_year,
        count(distinct org_slug)                              as n,
        avg(panel_per_clinician)                                   as mean_panel_per_clin,
        approx_quantiles(panel_per_clinician, 4)[offset(1)]       as p25_panel_per_clin,
        approx_quantiles(panel_per_clinician, 4)[offset(2)]       as p50_panel_per_clin,
        approx_quantiles(panel_per_clinician, 4)[offset(3)]       as p75_panel_per_clin,
        stddev(panel_per_clinician)                                as std_panel_per_clin,
        avg(cast(servicing_npi_count as float64))                  as mean_clinician_count,
        approx_quantiles(servicing_npi_count, 4)[offset(1)]       as p25_clinician_count,
        approx_quantiles(servicing_npi_count, 4)[offset(2)]       as p50_clinician_count,
        approx_quantiles(servicing_npi_count, 4)[offset(3)]       as p75_clinician_count,
        avg(claims_per_beneficiary)                                as mean_claims_per_bene,
        approx_quantiles(claims_per_beneficiary, 4)[offset(1)]    as p25_claims_per_bene,
        approx_quantiles(claims_per_beneficiary, 4)[offset(2)]    as p50_claims_per_bene,
        approx_quantiles(claims_per_beneficiary, 4)[offset(3)]    as p75_claims_per_bene,
        stddev(claims_per_beneficiary)                             as std_claims_per_bene,
        avg(payment_per_claim)                                     as mean_payment_per_claim,
        approx_quantiles(payment_per_claim, 4)[offset(1)]         as p25_payment_per_claim,
        approx_quantiles(payment_per_claim, 4)[offset(2)]         as p50_payment_per_claim,
        approx_quantiles(payment_per_claim, 4)[offset(3)]         as p75_payment_per_claim,
        stddev(payment_per_claim)                                  as std_payment_per_claim,
        avg(psychiatry_pct)    as avg_psychiatry_pct,
        avg(counselor_pct)     as avg_counselor_pct,
        avg(social_worker_pct) as avg_social_worker_pct,
        avg(mft_pct)           as avg_mft_pct,
        avg(psychologist_pct)  as avg_psychologist_pct,
        avg(aprn_pct)          as avg_aprn_pct,
        avg(market_share_pct)                                      as mean_market_share,
        approx_quantiles(market_share_pct, 4)[offset(1)]           as p25_market_share,
        approx_quantiles(market_share_pct, 4)[offset(2)]           as p50_market_share,
        approx_quantiles(market_share_pct, 4)[offset(3)]           as p75_market_share,
        avg(intake_market_share)                                    as mean_intake_market_share,
        approx_quantiles(intake_market_share, 4)[offset(1)]        as p25_intake_market_share,
        approx_quantiles(intake_market_share, 4)[offset(2)]        as p50_intake_market_share,
        approx_quantiles(intake_market_share, 4)[offset(3)]        as p75_intake_market_share,
        avg(high_acuity_market_share)                               as mean_high_acuity_market_share,
        approx_quantiles(high_acuity_market_share, 4)[offset(1)]   as p25_high_acuity_market_share,
        approx_quantiles(high_acuity_market_share, 4)[offset(2)]   as p50_high_acuity_market_share,
        approx_quantiles(high_acuity_market_share, 4)[offset(3)]   as p75_high_acuity_market_share,
        avg(ongoing_market_share)                                   as mean_ongoing_market_share,
        approx_quantiles(ongoing_market_share, 4)[offset(1)]       as p25_ongoing_market_share,
        approx_quantiles(ongoing_market_share, 4)[offset(2)]       as p50_ongoing_market_share,
        approx_quantiles(ongoing_market_share, 4)[offset(3)]       as p75_ongoing_market_share,
        avg(intake_revenue_pct)                                     as mean_intake_revenue_pct,
        approx_quantiles(intake_revenue_pct, 4)[offset(1)]         as p25_intake_revenue_pct,
        approx_quantiles(intake_revenue_pct, 4)[offset(2)]         as p50_intake_revenue_pct,
        approx_quantiles(intake_revenue_pct, 4)[offset(3)]         as p75_intake_revenue_pct,
        avg(high_acuity_revenue_pct)                                as mean_high_acuity_revenue_pct,
        approx_quantiles(high_acuity_revenue_pct, 4)[offset(1)]    as p25_high_acuity_revenue_pct,
        approx_quantiles(high_acuity_revenue_pct, 4)[offset(2)]    as p50_high_acuity_revenue_pct,
        approx_quantiles(high_acuity_revenue_pct, 4)[offset(3)]    as p75_high_acuity_revenue_pct,
        avg(ongoing_revenue_pct)                                    as mean_ongoing_revenue_pct,
        approx_quantiles(ongoing_revenue_pct, 4)[offset(1)]        as p25_ongoing_revenue_pct,
        approx_quantiles(ongoing_revenue_pct, 4)[offset(2)]        as p50_ongoing_revenue_pct,
        approx_quantiles(ongoing_revenue_pct, 4)[offset(3)]        as p75_ongoing_revenue_pct,
        avg(intake_bene_pct)                                        as mean_intake_bene_pct,
        approx_quantiles(intake_bene_pct, 4)[offset(1)]            as p25_intake_bene_pct,
        approx_quantiles(intake_bene_pct, 4)[offset(2)]            as p50_intake_bene_pct,
        approx_quantiles(intake_bene_pct, 4)[offset(3)]            as p75_intake_bene_pct,
        avg(high_acuity_bene_pct)                                   as mean_high_acuity_bene_pct,
        approx_quantiles(high_acuity_bene_pct, 4)[offset(1)]       as p25_high_acuity_bene_pct,
        approx_quantiles(high_acuity_bene_pct, 4)[offset(2)]       as p50_high_acuity_bene_pct,
        approx_quantiles(high_acuity_bene_pct, 4)[offset(3)]       as p75_high_acuity_bene_pct,
        avg(ongoing_bene_pct)                                       as mean_ongoing_bene_pct,
        approx_quantiles(ongoing_bene_pct, 4)[offset(1)]           as p25_ongoing_bene_pct,
        approx_quantiles(ongoing_bene_pct, 4)[offset(2)]           as p50_ongoing_bene_pct,
        approx_quantiles(ongoing_bene_pct, 4)[offset(3)]           as p75_ongoing_bene_pct
    from base where org_state != ''
    group by org_type, peer_group, size_band, market_tier, geo_level, geo_id, period_year
    having count(distinct org_slug) >= 3
),

to_zip as (
    select org_type, 'type_only' as peer_group,
        cast(null as string) as size_band, cast(null as string) as market_tier,
        'zip' as geo_level, org_zip5 as geo_id, period_year,
        count(distinct org_slug)                              as n,
        avg(panel_per_clinician)                                   as mean_panel_per_clin,
        approx_quantiles(panel_per_clinician, 4)[offset(1)]       as p25_panel_per_clin,
        approx_quantiles(panel_per_clinician, 4)[offset(2)]       as p50_panel_per_clin,
        approx_quantiles(panel_per_clinician, 4)[offset(3)]       as p75_panel_per_clin,
        stddev(panel_per_clinician)                                as std_panel_per_clin,
        avg(cast(servicing_npi_count as float64))                  as mean_clinician_count,
        approx_quantiles(servicing_npi_count, 4)[offset(1)]       as p25_clinician_count,
        approx_quantiles(servicing_npi_count, 4)[offset(2)]       as p50_clinician_count,
        approx_quantiles(servicing_npi_count, 4)[offset(3)]       as p75_clinician_count,
        avg(claims_per_beneficiary)                                as mean_claims_per_bene,
        approx_quantiles(claims_per_beneficiary, 4)[offset(1)]    as p25_claims_per_bene,
        approx_quantiles(claims_per_beneficiary, 4)[offset(2)]    as p50_claims_per_bene,
        approx_quantiles(claims_per_beneficiary, 4)[offset(3)]    as p75_claims_per_bene,
        stddev(claims_per_beneficiary)                             as std_claims_per_bene,
        avg(payment_per_claim)                                     as mean_payment_per_claim,
        approx_quantiles(payment_per_claim, 4)[offset(1)]         as p25_payment_per_claim,
        approx_quantiles(payment_per_claim, 4)[offset(2)]         as p50_payment_per_claim,
        approx_quantiles(payment_per_claim, 4)[offset(3)]         as p75_payment_per_claim,
        stddev(payment_per_claim)                                  as std_payment_per_claim,
        avg(psychiatry_pct)    as avg_psychiatry_pct,
        avg(counselor_pct)     as avg_counselor_pct,
        avg(social_worker_pct) as avg_social_worker_pct,
        avg(mft_pct)           as avg_mft_pct,
        avg(psychologist_pct)  as avg_psychologist_pct,
        avg(aprn_pct)          as avg_aprn_pct,
        avg(market_share_pct)                                      as mean_market_share,
        approx_quantiles(market_share_pct, 4)[offset(1)]           as p25_market_share,
        approx_quantiles(market_share_pct, 4)[offset(2)]           as p50_market_share,
        approx_quantiles(market_share_pct, 4)[offset(3)]           as p75_market_share,
        avg(intake_market_share)                                    as mean_intake_market_share,
        approx_quantiles(intake_market_share, 4)[offset(1)]        as p25_intake_market_share,
        approx_quantiles(intake_market_share, 4)[offset(2)]        as p50_intake_market_share,
        approx_quantiles(intake_market_share, 4)[offset(3)]        as p75_intake_market_share,
        avg(high_acuity_market_share)                               as mean_high_acuity_market_share,
        approx_quantiles(high_acuity_market_share, 4)[offset(1)]   as p25_high_acuity_market_share,
        approx_quantiles(high_acuity_market_share, 4)[offset(2)]   as p50_high_acuity_market_share,
        approx_quantiles(high_acuity_market_share, 4)[offset(3)]   as p75_high_acuity_market_share,
        avg(ongoing_market_share)                                   as mean_ongoing_market_share,
        approx_quantiles(ongoing_market_share, 4)[offset(1)]       as p25_ongoing_market_share,
        approx_quantiles(ongoing_market_share, 4)[offset(2)]       as p50_ongoing_market_share,
        approx_quantiles(ongoing_market_share, 4)[offset(3)]       as p75_ongoing_market_share,
        avg(intake_revenue_pct)                                     as mean_intake_revenue_pct,
        approx_quantiles(intake_revenue_pct, 4)[offset(1)]         as p25_intake_revenue_pct,
        approx_quantiles(intake_revenue_pct, 4)[offset(2)]         as p50_intake_revenue_pct,
        approx_quantiles(intake_revenue_pct, 4)[offset(3)]         as p75_intake_revenue_pct,
        avg(high_acuity_revenue_pct)                                as mean_high_acuity_revenue_pct,
        approx_quantiles(high_acuity_revenue_pct, 4)[offset(1)]    as p25_high_acuity_revenue_pct,
        approx_quantiles(high_acuity_revenue_pct, 4)[offset(2)]    as p50_high_acuity_revenue_pct,
        approx_quantiles(high_acuity_revenue_pct, 4)[offset(3)]    as p75_high_acuity_revenue_pct,
        avg(ongoing_revenue_pct)                                    as mean_ongoing_revenue_pct,
        approx_quantiles(ongoing_revenue_pct, 4)[offset(1)]        as p25_ongoing_revenue_pct,
        approx_quantiles(ongoing_revenue_pct, 4)[offset(2)]        as p50_ongoing_revenue_pct,
        approx_quantiles(ongoing_revenue_pct, 4)[offset(3)]        as p75_ongoing_revenue_pct,
        avg(intake_bene_pct)                                        as mean_intake_bene_pct,
        approx_quantiles(intake_bene_pct, 4)[offset(1)]            as p25_intake_bene_pct,
        approx_quantiles(intake_bene_pct, 4)[offset(2)]            as p50_intake_bene_pct,
        approx_quantiles(intake_bene_pct, 4)[offset(3)]            as p75_intake_bene_pct,
        avg(high_acuity_bene_pct)                                   as mean_high_acuity_bene_pct,
        approx_quantiles(high_acuity_bene_pct, 4)[offset(1)]       as p25_high_acuity_bene_pct,
        approx_quantiles(high_acuity_bene_pct, 4)[offset(2)]       as p50_high_acuity_bene_pct,
        approx_quantiles(high_acuity_bene_pct, 4)[offset(3)]       as p75_high_acuity_bene_pct,
        avg(ongoing_bene_pct)                                       as mean_ongoing_bene_pct,
        approx_quantiles(ongoing_bene_pct, 4)[offset(1)]           as p25_ongoing_bene_pct,
        approx_quantiles(ongoing_bene_pct, 4)[offset(2)]           as p50_ongoing_bene_pct,
        approx_quantiles(ongoing_bene_pct, 4)[offset(3)]           as p75_ongoing_bene_pct
    from base where org_zip5 != ''
    group by org_type, peer_group, size_band, market_tier, geo_level, geo_id, period_year
    having count(distinct org_slug) >= 3
),

-- ── type_size — org_type + size_band ─────────────────────────────────────────

ts_national as (
    select org_type, 'type_size' as peer_group,
        size_band, cast(null as string) as market_tier,
        'national' as geo_level, 'US' as geo_id, period_year,
        count(distinct org_slug)                              as n,
        avg(panel_per_clinician)                                   as mean_panel_per_clin,
        approx_quantiles(panel_per_clinician, 4)[offset(1)]       as p25_panel_per_clin,
        approx_quantiles(panel_per_clinician, 4)[offset(2)]       as p50_panel_per_clin,
        approx_quantiles(panel_per_clinician, 4)[offset(3)]       as p75_panel_per_clin,
        stddev(panel_per_clinician)                                as std_panel_per_clin,
        avg(cast(servicing_npi_count as float64))                  as mean_clinician_count,
        approx_quantiles(servicing_npi_count, 4)[offset(1)]       as p25_clinician_count,
        approx_quantiles(servicing_npi_count, 4)[offset(2)]       as p50_clinician_count,
        approx_quantiles(servicing_npi_count, 4)[offset(3)]       as p75_clinician_count,
        avg(claims_per_beneficiary)                                as mean_claims_per_bene,
        approx_quantiles(claims_per_beneficiary, 4)[offset(1)]    as p25_claims_per_bene,
        approx_quantiles(claims_per_beneficiary, 4)[offset(2)]    as p50_claims_per_bene,
        approx_quantiles(claims_per_beneficiary, 4)[offset(3)]    as p75_claims_per_bene,
        stddev(claims_per_beneficiary)                             as std_claims_per_bene,
        avg(payment_per_claim)                                     as mean_payment_per_claim,
        approx_quantiles(payment_per_claim, 4)[offset(1)]         as p25_payment_per_claim,
        approx_quantiles(payment_per_claim, 4)[offset(2)]         as p50_payment_per_claim,
        approx_quantiles(payment_per_claim, 4)[offset(3)]         as p75_payment_per_claim,
        stddev(payment_per_claim)                                  as std_payment_per_claim,
        avg(psychiatry_pct)    as avg_psychiatry_pct,
        avg(counselor_pct)     as avg_counselor_pct,
        avg(social_worker_pct) as avg_social_worker_pct,
        avg(mft_pct)           as avg_mft_pct,
        avg(psychologist_pct)  as avg_psychologist_pct,
        avg(aprn_pct)          as avg_aprn_pct,
        avg(market_share_pct)                                      as mean_market_share,
        approx_quantiles(market_share_pct, 4)[offset(1)]           as p25_market_share,
        approx_quantiles(market_share_pct, 4)[offset(2)]           as p50_market_share,
        approx_quantiles(market_share_pct, 4)[offset(3)]           as p75_market_share,
        avg(intake_market_share)                                    as mean_intake_market_share,
        approx_quantiles(intake_market_share, 4)[offset(1)]        as p25_intake_market_share,
        approx_quantiles(intake_market_share, 4)[offset(2)]        as p50_intake_market_share,
        approx_quantiles(intake_market_share, 4)[offset(3)]        as p75_intake_market_share,
        avg(high_acuity_market_share)                               as mean_high_acuity_market_share,
        approx_quantiles(high_acuity_market_share, 4)[offset(1)]   as p25_high_acuity_market_share,
        approx_quantiles(high_acuity_market_share, 4)[offset(2)]   as p50_high_acuity_market_share,
        approx_quantiles(high_acuity_market_share, 4)[offset(3)]   as p75_high_acuity_market_share,
        avg(ongoing_market_share)                                   as mean_ongoing_market_share,
        approx_quantiles(ongoing_market_share, 4)[offset(1)]       as p25_ongoing_market_share,
        approx_quantiles(ongoing_market_share, 4)[offset(2)]       as p50_ongoing_market_share,
        approx_quantiles(ongoing_market_share, 4)[offset(3)]       as p75_ongoing_market_share,
        avg(intake_revenue_pct)                                     as mean_intake_revenue_pct,
        approx_quantiles(intake_revenue_pct, 4)[offset(1)]         as p25_intake_revenue_pct,
        approx_quantiles(intake_revenue_pct, 4)[offset(2)]         as p50_intake_revenue_pct,
        approx_quantiles(intake_revenue_pct, 4)[offset(3)]         as p75_intake_revenue_pct,
        avg(high_acuity_revenue_pct)                                as mean_high_acuity_revenue_pct,
        approx_quantiles(high_acuity_revenue_pct, 4)[offset(1)]    as p25_high_acuity_revenue_pct,
        approx_quantiles(high_acuity_revenue_pct, 4)[offset(2)]    as p50_high_acuity_revenue_pct,
        approx_quantiles(high_acuity_revenue_pct, 4)[offset(3)]    as p75_high_acuity_revenue_pct,
        avg(ongoing_revenue_pct)                                    as mean_ongoing_revenue_pct,
        approx_quantiles(ongoing_revenue_pct, 4)[offset(1)]        as p25_ongoing_revenue_pct,
        approx_quantiles(ongoing_revenue_pct, 4)[offset(2)]        as p50_ongoing_revenue_pct,
        approx_quantiles(ongoing_revenue_pct, 4)[offset(3)]        as p75_ongoing_revenue_pct,
        avg(intake_bene_pct)                                        as mean_intake_bene_pct,
        approx_quantiles(intake_bene_pct, 4)[offset(1)]            as p25_intake_bene_pct,
        approx_quantiles(intake_bene_pct, 4)[offset(2)]            as p50_intake_bene_pct,
        approx_quantiles(intake_bene_pct, 4)[offset(3)]            as p75_intake_bene_pct,
        avg(high_acuity_bene_pct)                                   as mean_high_acuity_bene_pct,
        approx_quantiles(high_acuity_bene_pct, 4)[offset(1)]       as p25_high_acuity_bene_pct,
        approx_quantiles(high_acuity_bene_pct, 4)[offset(2)]       as p50_high_acuity_bene_pct,
        approx_quantiles(high_acuity_bene_pct, 4)[offset(3)]       as p75_high_acuity_bene_pct,
        avg(ongoing_bene_pct)                                       as mean_ongoing_bene_pct,
        approx_quantiles(ongoing_bene_pct, 4)[offset(1)]           as p25_ongoing_bene_pct,
        approx_quantiles(ongoing_bene_pct, 4)[offset(2)]           as p50_ongoing_bene_pct,
        approx_quantiles(ongoing_bene_pct, 4)[offset(3)]           as p75_ongoing_bene_pct
    from base
    group by org_type, peer_group, size_band, market_tier, geo_level, geo_id, period_year
    having count(distinct org_slug) >= 3
),

ts_state as (
    select org_type, 'type_size' as peer_group,
        size_band, cast(null as string) as market_tier,
        'state' as geo_level, org_state as geo_id, period_year,
        count(distinct org_slug)                              as n,
        avg(panel_per_clinician)                                   as mean_panel_per_clin,
        approx_quantiles(panel_per_clinician, 4)[offset(1)]       as p25_panel_per_clin,
        approx_quantiles(panel_per_clinician, 4)[offset(2)]       as p50_panel_per_clin,
        approx_quantiles(panel_per_clinician, 4)[offset(3)]       as p75_panel_per_clin,
        stddev(panel_per_clinician)                                as std_panel_per_clin,
        avg(cast(servicing_npi_count as float64))                  as mean_clinician_count,
        approx_quantiles(servicing_npi_count, 4)[offset(1)]       as p25_clinician_count,
        approx_quantiles(servicing_npi_count, 4)[offset(2)]       as p50_clinician_count,
        approx_quantiles(servicing_npi_count, 4)[offset(3)]       as p75_clinician_count,
        avg(claims_per_beneficiary)                                as mean_claims_per_bene,
        approx_quantiles(claims_per_beneficiary, 4)[offset(1)]    as p25_claims_per_bene,
        approx_quantiles(claims_per_beneficiary, 4)[offset(2)]    as p50_claims_per_bene,
        approx_quantiles(claims_per_beneficiary, 4)[offset(3)]    as p75_claims_per_bene,
        stddev(claims_per_beneficiary)                             as std_claims_per_bene,
        avg(payment_per_claim)                                     as mean_payment_per_claim,
        approx_quantiles(payment_per_claim, 4)[offset(1)]         as p25_payment_per_claim,
        approx_quantiles(payment_per_claim, 4)[offset(2)]         as p50_payment_per_claim,
        approx_quantiles(payment_per_claim, 4)[offset(3)]         as p75_payment_per_claim,
        stddev(payment_per_claim)                                  as std_payment_per_claim,
        avg(psychiatry_pct)    as avg_psychiatry_pct,
        avg(counselor_pct)     as avg_counselor_pct,
        avg(social_worker_pct) as avg_social_worker_pct,
        avg(mft_pct)           as avg_mft_pct,
        avg(psychologist_pct)  as avg_psychologist_pct,
        avg(aprn_pct)          as avg_aprn_pct,
        avg(market_share_pct)                                      as mean_market_share,
        approx_quantiles(market_share_pct, 4)[offset(1)]           as p25_market_share,
        approx_quantiles(market_share_pct, 4)[offset(2)]           as p50_market_share,
        approx_quantiles(market_share_pct, 4)[offset(3)]           as p75_market_share,
        avg(intake_market_share)                                    as mean_intake_market_share,
        approx_quantiles(intake_market_share, 4)[offset(1)]        as p25_intake_market_share,
        approx_quantiles(intake_market_share, 4)[offset(2)]        as p50_intake_market_share,
        approx_quantiles(intake_market_share, 4)[offset(3)]        as p75_intake_market_share,
        avg(high_acuity_market_share)                               as mean_high_acuity_market_share,
        approx_quantiles(high_acuity_market_share, 4)[offset(1)]   as p25_high_acuity_market_share,
        approx_quantiles(high_acuity_market_share, 4)[offset(2)]   as p50_high_acuity_market_share,
        approx_quantiles(high_acuity_market_share, 4)[offset(3)]   as p75_high_acuity_market_share,
        avg(ongoing_market_share)                                   as mean_ongoing_market_share,
        approx_quantiles(ongoing_market_share, 4)[offset(1)]       as p25_ongoing_market_share,
        approx_quantiles(ongoing_market_share, 4)[offset(2)]       as p50_ongoing_market_share,
        approx_quantiles(ongoing_market_share, 4)[offset(3)]       as p75_ongoing_market_share,
        avg(intake_revenue_pct)                                     as mean_intake_revenue_pct,
        approx_quantiles(intake_revenue_pct, 4)[offset(1)]         as p25_intake_revenue_pct,
        approx_quantiles(intake_revenue_pct, 4)[offset(2)]         as p50_intake_revenue_pct,
        approx_quantiles(intake_revenue_pct, 4)[offset(3)]         as p75_intake_revenue_pct,
        avg(high_acuity_revenue_pct)                                as mean_high_acuity_revenue_pct,
        approx_quantiles(high_acuity_revenue_pct, 4)[offset(1)]    as p25_high_acuity_revenue_pct,
        approx_quantiles(high_acuity_revenue_pct, 4)[offset(2)]    as p50_high_acuity_revenue_pct,
        approx_quantiles(high_acuity_revenue_pct, 4)[offset(3)]    as p75_high_acuity_revenue_pct,
        avg(ongoing_revenue_pct)                                    as mean_ongoing_revenue_pct,
        approx_quantiles(ongoing_revenue_pct, 4)[offset(1)]        as p25_ongoing_revenue_pct,
        approx_quantiles(ongoing_revenue_pct, 4)[offset(2)]        as p50_ongoing_revenue_pct,
        approx_quantiles(ongoing_revenue_pct, 4)[offset(3)]        as p75_ongoing_revenue_pct,
        avg(intake_bene_pct)                                        as mean_intake_bene_pct,
        approx_quantiles(intake_bene_pct, 4)[offset(1)]            as p25_intake_bene_pct,
        approx_quantiles(intake_bene_pct, 4)[offset(2)]            as p50_intake_bene_pct,
        approx_quantiles(intake_bene_pct, 4)[offset(3)]            as p75_intake_bene_pct,
        avg(high_acuity_bene_pct)                                   as mean_high_acuity_bene_pct,
        approx_quantiles(high_acuity_bene_pct, 4)[offset(1)]       as p25_high_acuity_bene_pct,
        approx_quantiles(high_acuity_bene_pct, 4)[offset(2)]       as p50_high_acuity_bene_pct,
        approx_quantiles(high_acuity_bene_pct, 4)[offset(3)]       as p75_high_acuity_bene_pct,
        avg(ongoing_bene_pct)                                       as mean_ongoing_bene_pct,
        approx_quantiles(ongoing_bene_pct, 4)[offset(1)]           as p25_ongoing_bene_pct,
        approx_quantiles(ongoing_bene_pct, 4)[offset(2)]           as p50_ongoing_bene_pct,
        approx_quantiles(ongoing_bene_pct, 4)[offset(3)]           as p75_ongoing_bene_pct
    from base where org_state != ''
    group by org_type, peer_group, size_band, market_tier, geo_level, geo_id, period_year
    having count(distinct org_slug) >= 3
),

ts_zip as (
    select org_type, 'type_size' as peer_group,
        size_band, cast(null as string) as market_tier,
        'zip' as geo_level, org_zip5 as geo_id, period_year,
        count(distinct org_slug)                              as n,
        avg(panel_per_clinician)                                   as mean_panel_per_clin,
        approx_quantiles(panel_per_clinician, 4)[offset(1)]       as p25_panel_per_clin,
        approx_quantiles(panel_per_clinician, 4)[offset(2)]       as p50_panel_per_clin,
        approx_quantiles(panel_per_clinician, 4)[offset(3)]       as p75_panel_per_clin,
        stddev(panel_per_clinician)                                as std_panel_per_clin,
        avg(cast(servicing_npi_count as float64))                  as mean_clinician_count,
        approx_quantiles(servicing_npi_count, 4)[offset(1)]       as p25_clinician_count,
        approx_quantiles(servicing_npi_count, 4)[offset(2)]       as p50_clinician_count,
        approx_quantiles(servicing_npi_count, 4)[offset(3)]       as p75_clinician_count,
        avg(claims_per_beneficiary)                                as mean_claims_per_bene,
        approx_quantiles(claims_per_beneficiary, 4)[offset(1)]    as p25_claims_per_bene,
        approx_quantiles(claims_per_beneficiary, 4)[offset(2)]    as p50_claims_per_bene,
        approx_quantiles(claims_per_beneficiary, 4)[offset(3)]    as p75_claims_per_bene,
        stddev(claims_per_beneficiary)                             as std_claims_per_bene,
        avg(payment_per_claim)                                     as mean_payment_per_claim,
        approx_quantiles(payment_per_claim, 4)[offset(1)]         as p25_payment_per_claim,
        approx_quantiles(payment_per_claim, 4)[offset(2)]         as p50_payment_per_claim,
        approx_quantiles(payment_per_claim, 4)[offset(3)]         as p75_payment_per_claim,
        stddev(payment_per_claim)                                  as std_payment_per_claim,
        avg(psychiatry_pct)    as avg_psychiatry_pct,
        avg(counselor_pct)     as avg_counselor_pct,
        avg(social_worker_pct) as avg_social_worker_pct,
        avg(mft_pct)           as avg_mft_pct,
        avg(psychologist_pct)  as avg_psychologist_pct,
        avg(aprn_pct)          as avg_aprn_pct,
        avg(market_share_pct)                                      as mean_market_share,
        approx_quantiles(market_share_pct, 4)[offset(1)]           as p25_market_share,
        approx_quantiles(market_share_pct, 4)[offset(2)]           as p50_market_share,
        approx_quantiles(market_share_pct, 4)[offset(3)]           as p75_market_share,
        avg(intake_market_share)                                    as mean_intake_market_share,
        approx_quantiles(intake_market_share, 4)[offset(1)]        as p25_intake_market_share,
        approx_quantiles(intake_market_share, 4)[offset(2)]        as p50_intake_market_share,
        approx_quantiles(intake_market_share, 4)[offset(3)]        as p75_intake_market_share,
        avg(high_acuity_market_share)                               as mean_high_acuity_market_share,
        approx_quantiles(high_acuity_market_share, 4)[offset(1)]   as p25_high_acuity_market_share,
        approx_quantiles(high_acuity_market_share, 4)[offset(2)]   as p50_high_acuity_market_share,
        approx_quantiles(high_acuity_market_share, 4)[offset(3)]   as p75_high_acuity_market_share,
        avg(ongoing_market_share)                                   as mean_ongoing_market_share,
        approx_quantiles(ongoing_market_share, 4)[offset(1)]       as p25_ongoing_market_share,
        approx_quantiles(ongoing_market_share, 4)[offset(2)]       as p50_ongoing_market_share,
        approx_quantiles(ongoing_market_share, 4)[offset(3)]       as p75_ongoing_market_share,
        avg(intake_revenue_pct)                                     as mean_intake_revenue_pct,
        approx_quantiles(intake_revenue_pct, 4)[offset(1)]         as p25_intake_revenue_pct,
        approx_quantiles(intake_revenue_pct, 4)[offset(2)]         as p50_intake_revenue_pct,
        approx_quantiles(intake_revenue_pct, 4)[offset(3)]         as p75_intake_revenue_pct,
        avg(high_acuity_revenue_pct)                                as mean_high_acuity_revenue_pct,
        approx_quantiles(high_acuity_revenue_pct, 4)[offset(1)]    as p25_high_acuity_revenue_pct,
        approx_quantiles(high_acuity_revenue_pct, 4)[offset(2)]    as p50_high_acuity_revenue_pct,
        approx_quantiles(high_acuity_revenue_pct, 4)[offset(3)]    as p75_high_acuity_revenue_pct,
        avg(ongoing_revenue_pct)                                    as mean_ongoing_revenue_pct,
        approx_quantiles(ongoing_revenue_pct, 4)[offset(1)]        as p25_ongoing_revenue_pct,
        approx_quantiles(ongoing_revenue_pct, 4)[offset(2)]        as p50_ongoing_revenue_pct,
        approx_quantiles(ongoing_revenue_pct, 4)[offset(3)]        as p75_ongoing_revenue_pct,
        avg(intake_bene_pct)                                        as mean_intake_bene_pct,
        approx_quantiles(intake_bene_pct, 4)[offset(1)]            as p25_intake_bene_pct,
        approx_quantiles(intake_bene_pct, 4)[offset(2)]            as p50_intake_bene_pct,
        approx_quantiles(intake_bene_pct, 4)[offset(3)]            as p75_intake_bene_pct,
        avg(high_acuity_bene_pct)                                   as mean_high_acuity_bene_pct,
        approx_quantiles(high_acuity_bene_pct, 4)[offset(1)]       as p25_high_acuity_bene_pct,
        approx_quantiles(high_acuity_bene_pct, 4)[offset(2)]       as p50_high_acuity_bene_pct,
        approx_quantiles(high_acuity_bene_pct, 4)[offset(3)]       as p75_high_acuity_bene_pct,
        avg(ongoing_bene_pct)                                       as mean_ongoing_bene_pct,
        approx_quantiles(ongoing_bene_pct, 4)[offset(1)]           as p25_ongoing_bene_pct,
        approx_quantiles(ongoing_bene_pct, 4)[offset(2)]           as p50_ongoing_bene_pct,
        approx_quantiles(ongoing_bene_pct, 4)[offset(3)]           as p75_ongoing_bene_pct
    from base where org_zip5 != ''
    group by org_type, peer_group, size_band, market_tier, geo_level, geo_id, period_year
    having count(distinct org_slug) >= 3
),

-- ── type_market — org_type + market_tier ─────────────────────────────────────

tm_national as (
    select org_type, 'type_market' as peer_group,
        cast(null as string) as size_band, market_tier,
        'national' as geo_level, 'US' as geo_id, period_year,
        count(distinct org_slug)                              as n,
        avg(panel_per_clinician)                                   as mean_panel_per_clin,
        approx_quantiles(panel_per_clinician, 4)[offset(1)]       as p25_panel_per_clin,
        approx_quantiles(panel_per_clinician, 4)[offset(2)]       as p50_panel_per_clin,
        approx_quantiles(panel_per_clinician, 4)[offset(3)]       as p75_panel_per_clin,
        stddev(panel_per_clinician)                                as std_panel_per_clin,
        avg(cast(servicing_npi_count as float64))                  as mean_clinician_count,
        approx_quantiles(servicing_npi_count, 4)[offset(1)]       as p25_clinician_count,
        approx_quantiles(servicing_npi_count, 4)[offset(2)]       as p50_clinician_count,
        approx_quantiles(servicing_npi_count, 4)[offset(3)]       as p75_clinician_count,
        avg(claims_per_beneficiary)                                as mean_claims_per_bene,
        approx_quantiles(claims_per_beneficiary, 4)[offset(1)]    as p25_claims_per_bene,
        approx_quantiles(claims_per_beneficiary, 4)[offset(2)]    as p50_claims_per_bene,
        approx_quantiles(claims_per_beneficiary, 4)[offset(3)]    as p75_claims_per_bene,
        stddev(claims_per_beneficiary)                             as std_claims_per_bene,
        avg(payment_per_claim)                                     as mean_payment_per_claim,
        approx_quantiles(payment_per_claim, 4)[offset(1)]         as p25_payment_per_claim,
        approx_quantiles(payment_per_claim, 4)[offset(2)]         as p50_payment_per_claim,
        approx_quantiles(payment_per_claim, 4)[offset(3)]         as p75_payment_per_claim,
        stddev(payment_per_claim)                                  as std_payment_per_claim,
        avg(psychiatry_pct)    as avg_psychiatry_pct,
        avg(counselor_pct)     as avg_counselor_pct,
        avg(social_worker_pct) as avg_social_worker_pct,
        avg(mft_pct)           as avg_mft_pct,
        avg(psychologist_pct)  as avg_psychologist_pct,
        avg(aprn_pct)          as avg_aprn_pct,
        avg(market_share_pct)                                      as mean_market_share,
        approx_quantiles(market_share_pct, 4)[offset(1)]           as p25_market_share,
        approx_quantiles(market_share_pct, 4)[offset(2)]           as p50_market_share,
        approx_quantiles(market_share_pct, 4)[offset(3)]           as p75_market_share,
        avg(intake_market_share)                                    as mean_intake_market_share,
        approx_quantiles(intake_market_share, 4)[offset(1)]        as p25_intake_market_share,
        approx_quantiles(intake_market_share, 4)[offset(2)]        as p50_intake_market_share,
        approx_quantiles(intake_market_share, 4)[offset(3)]        as p75_intake_market_share,
        avg(high_acuity_market_share)                               as mean_high_acuity_market_share,
        approx_quantiles(high_acuity_market_share, 4)[offset(1)]   as p25_high_acuity_market_share,
        approx_quantiles(high_acuity_market_share, 4)[offset(2)]   as p50_high_acuity_market_share,
        approx_quantiles(high_acuity_market_share, 4)[offset(3)]   as p75_high_acuity_market_share,
        avg(ongoing_market_share)                                   as mean_ongoing_market_share,
        approx_quantiles(ongoing_market_share, 4)[offset(1)]       as p25_ongoing_market_share,
        approx_quantiles(ongoing_market_share, 4)[offset(2)]       as p50_ongoing_market_share,
        approx_quantiles(ongoing_market_share, 4)[offset(3)]       as p75_ongoing_market_share,
        avg(intake_revenue_pct)                                     as mean_intake_revenue_pct,
        approx_quantiles(intake_revenue_pct, 4)[offset(1)]         as p25_intake_revenue_pct,
        approx_quantiles(intake_revenue_pct, 4)[offset(2)]         as p50_intake_revenue_pct,
        approx_quantiles(intake_revenue_pct, 4)[offset(3)]         as p75_intake_revenue_pct,
        avg(high_acuity_revenue_pct)                                as mean_high_acuity_revenue_pct,
        approx_quantiles(high_acuity_revenue_pct, 4)[offset(1)]    as p25_high_acuity_revenue_pct,
        approx_quantiles(high_acuity_revenue_pct, 4)[offset(2)]    as p50_high_acuity_revenue_pct,
        approx_quantiles(high_acuity_revenue_pct, 4)[offset(3)]    as p75_high_acuity_revenue_pct,
        avg(ongoing_revenue_pct)                                    as mean_ongoing_revenue_pct,
        approx_quantiles(ongoing_revenue_pct, 4)[offset(1)]        as p25_ongoing_revenue_pct,
        approx_quantiles(ongoing_revenue_pct, 4)[offset(2)]        as p50_ongoing_revenue_pct,
        approx_quantiles(ongoing_revenue_pct, 4)[offset(3)]        as p75_ongoing_revenue_pct,
        avg(intake_bene_pct)                                        as mean_intake_bene_pct,
        approx_quantiles(intake_bene_pct, 4)[offset(1)]            as p25_intake_bene_pct,
        approx_quantiles(intake_bene_pct, 4)[offset(2)]            as p50_intake_bene_pct,
        approx_quantiles(intake_bene_pct, 4)[offset(3)]            as p75_intake_bene_pct,
        avg(high_acuity_bene_pct)                                   as mean_high_acuity_bene_pct,
        approx_quantiles(high_acuity_bene_pct, 4)[offset(1)]       as p25_high_acuity_bene_pct,
        approx_quantiles(high_acuity_bene_pct, 4)[offset(2)]       as p50_high_acuity_bene_pct,
        approx_quantiles(high_acuity_bene_pct, 4)[offset(3)]       as p75_high_acuity_bene_pct,
        avg(ongoing_bene_pct)                                       as mean_ongoing_bene_pct,
        approx_quantiles(ongoing_bene_pct, 4)[offset(1)]           as p25_ongoing_bene_pct,
        approx_quantiles(ongoing_bene_pct, 4)[offset(2)]           as p50_ongoing_bene_pct,
        approx_quantiles(ongoing_bene_pct, 4)[offset(3)]           as p75_ongoing_bene_pct
    from base
    group by org_type, peer_group, size_band, market_tier, geo_level, geo_id, period_year
    having count(distinct org_slug) >= 3
),

tm_state as (
    select org_type, 'type_market' as peer_group,
        cast(null as string) as size_band, market_tier,
        'state' as geo_level, org_state as geo_id, period_year,
        count(distinct org_slug)                              as n,
        avg(panel_per_clinician)                                   as mean_panel_per_clin,
        approx_quantiles(panel_per_clinician, 4)[offset(1)]       as p25_panel_per_clin,
        approx_quantiles(panel_per_clinician, 4)[offset(2)]       as p50_panel_per_clin,
        approx_quantiles(panel_per_clinician, 4)[offset(3)]       as p75_panel_per_clin,
        stddev(panel_per_clinician)                                as std_panel_per_clin,
        avg(cast(servicing_npi_count as float64))                  as mean_clinician_count,
        approx_quantiles(servicing_npi_count, 4)[offset(1)]       as p25_clinician_count,
        approx_quantiles(servicing_npi_count, 4)[offset(2)]       as p50_clinician_count,
        approx_quantiles(servicing_npi_count, 4)[offset(3)]       as p75_clinician_count,
        avg(claims_per_beneficiary)                                as mean_claims_per_bene,
        approx_quantiles(claims_per_beneficiary, 4)[offset(1)]    as p25_claims_per_bene,
        approx_quantiles(claims_per_beneficiary, 4)[offset(2)]    as p50_claims_per_bene,
        approx_quantiles(claims_per_beneficiary, 4)[offset(3)]    as p75_claims_per_bene,
        stddev(claims_per_beneficiary)                             as std_claims_per_bene,
        avg(payment_per_claim)                                     as mean_payment_per_claim,
        approx_quantiles(payment_per_claim, 4)[offset(1)]         as p25_payment_per_claim,
        approx_quantiles(payment_per_claim, 4)[offset(2)]         as p50_payment_per_claim,
        approx_quantiles(payment_per_claim, 4)[offset(3)]         as p75_payment_per_claim,
        stddev(payment_per_claim)                                  as std_payment_per_claim,
        avg(psychiatry_pct)    as avg_psychiatry_pct,
        avg(counselor_pct)     as avg_counselor_pct,
        avg(social_worker_pct) as avg_social_worker_pct,
        avg(mft_pct)           as avg_mft_pct,
        avg(psychologist_pct)  as avg_psychologist_pct,
        avg(aprn_pct)          as avg_aprn_pct,
        avg(market_share_pct)                                      as mean_market_share,
        approx_quantiles(market_share_pct, 4)[offset(1)]           as p25_market_share,
        approx_quantiles(market_share_pct, 4)[offset(2)]           as p50_market_share,
        approx_quantiles(market_share_pct, 4)[offset(3)]           as p75_market_share,
        avg(intake_market_share)                                    as mean_intake_market_share,
        approx_quantiles(intake_market_share, 4)[offset(1)]        as p25_intake_market_share,
        approx_quantiles(intake_market_share, 4)[offset(2)]        as p50_intake_market_share,
        approx_quantiles(intake_market_share, 4)[offset(3)]        as p75_intake_market_share,
        avg(high_acuity_market_share)                               as mean_high_acuity_market_share,
        approx_quantiles(high_acuity_market_share, 4)[offset(1)]   as p25_high_acuity_market_share,
        approx_quantiles(high_acuity_market_share, 4)[offset(2)]   as p50_high_acuity_market_share,
        approx_quantiles(high_acuity_market_share, 4)[offset(3)]   as p75_high_acuity_market_share,
        avg(ongoing_market_share)                                   as mean_ongoing_market_share,
        approx_quantiles(ongoing_market_share, 4)[offset(1)]       as p25_ongoing_market_share,
        approx_quantiles(ongoing_market_share, 4)[offset(2)]       as p50_ongoing_market_share,
        approx_quantiles(ongoing_market_share, 4)[offset(3)]       as p75_ongoing_market_share,
        avg(intake_revenue_pct)                                     as mean_intake_revenue_pct,
        approx_quantiles(intake_revenue_pct, 4)[offset(1)]         as p25_intake_revenue_pct,
        approx_quantiles(intake_revenue_pct, 4)[offset(2)]         as p50_intake_revenue_pct,
        approx_quantiles(intake_revenue_pct, 4)[offset(3)]         as p75_intake_revenue_pct,
        avg(high_acuity_revenue_pct)                                as mean_high_acuity_revenue_pct,
        approx_quantiles(high_acuity_revenue_pct, 4)[offset(1)]    as p25_high_acuity_revenue_pct,
        approx_quantiles(high_acuity_revenue_pct, 4)[offset(2)]    as p50_high_acuity_revenue_pct,
        approx_quantiles(high_acuity_revenue_pct, 4)[offset(3)]    as p75_high_acuity_revenue_pct,
        avg(ongoing_revenue_pct)                                    as mean_ongoing_revenue_pct,
        approx_quantiles(ongoing_revenue_pct, 4)[offset(1)]        as p25_ongoing_revenue_pct,
        approx_quantiles(ongoing_revenue_pct, 4)[offset(2)]        as p50_ongoing_revenue_pct,
        approx_quantiles(ongoing_revenue_pct, 4)[offset(3)]        as p75_ongoing_revenue_pct,
        avg(intake_bene_pct)                                        as mean_intake_bene_pct,
        approx_quantiles(intake_bene_pct, 4)[offset(1)]            as p25_intake_bene_pct,
        approx_quantiles(intake_bene_pct, 4)[offset(2)]            as p50_intake_bene_pct,
        approx_quantiles(intake_bene_pct, 4)[offset(3)]            as p75_intake_bene_pct,
        avg(high_acuity_bene_pct)                                   as mean_high_acuity_bene_pct,
        approx_quantiles(high_acuity_bene_pct, 4)[offset(1)]       as p25_high_acuity_bene_pct,
        approx_quantiles(high_acuity_bene_pct, 4)[offset(2)]       as p50_high_acuity_bene_pct,
        approx_quantiles(high_acuity_bene_pct, 4)[offset(3)]       as p75_high_acuity_bene_pct,
        avg(ongoing_bene_pct)                                       as mean_ongoing_bene_pct,
        approx_quantiles(ongoing_bene_pct, 4)[offset(1)]           as p25_ongoing_bene_pct,
        approx_quantiles(ongoing_bene_pct, 4)[offset(2)]           as p50_ongoing_bene_pct,
        approx_quantiles(ongoing_bene_pct, 4)[offset(3)]           as p75_ongoing_bene_pct
    from base where org_state != ''
    group by org_type, peer_group, size_band, market_tier, geo_level, geo_id, period_year
    having count(distinct org_slug) >= 3
),

tm_zip as (
    select org_type, 'type_market' as peer_group,
        cast(null as string) as size_band, market_tier,
        'zip' as geo_level, org_zip5 as geo_id, period_year,
        count(distinct org_slug)                              as n,
        avg(panel_per_clinician)                                   as mean_panel_per_clin,
        approx_quantiles(panel_per_clinician, 4)[offset(1)]       as p25_panel_per_clin,
        approx_quantiles(panel_per_clinician, 4)[offset(2)]       as p50_panel_per_clin,
        approx_quantiles(panel_per_clinician, 4)[offset(3)]       as p75_panel_per_clin,
        stddev(panel_per_clinician)                                as std_panel_per_clin,
        avg(cast(servicing_npi_count as float64))                  as mean_clinician_count,
        approx_quantiles(servicing_npi_count, 4)[offset(1)]       as p25_clinician_count,
        approx_quantiles(servicing_npi_count, 4)[offset(2)]       as p50_clinician_count,
        approx_quantiles(servicing_npi_count, 4)[offset(3)]       as p75_clinician_count,
        avg(claims_per_beneficiary)                                as mean_claims_per_bene,
        approx_quantiles(claims_per_beneficiary, 4)[offset(1)]    as p25_claims_per_bene,
        approx_quantiles(claims_per_beneficiary, 4)[offset(2)]    as p50_claims_per_bene,
        approx_quantiles(claims_per_beneficiary, 4)[offset(3)]    as p75_claims_per_bene,
        stddev(claims_per_beneficiary)                             as std_claims_per_bene,
        avg(payment_per_claim)                                     as mean_payment_per_claim,
        approx_quantiles(payment_per_claim, 4)[offset(1)]         as p25_payment_per_claim,
        approx_quantiles(payment_per_claim, 4)[offset(2)]         as p50_payment_per_claim,
        approx_quantiles(payment_per_claim, 4)[offset(3)]         as p75_payment_per_claim,
        stddev(payment_per_claim)                                  as std_payment_per_claim,
        avg(psychiatry_pct)    as avg_psychiatry_pct,
        avg(counselor_pct)     as avg_counselor_pct,
        avg(social_worker_pct) as avg_social_worker_pct,
        avg(mft_pct)           as avg_mft_pct,
        avg(psychologist_pct)  as avg_psychologist_pct,
        avg(aprn_pct)          as avg_aprn_pct,
        avg(market_share_pct)                                      as mean_market_share,
        approx_quantiles(market_share_pct, 4)[offset(1)]           as p25_market_share,
        approx_quantiles(market_share_pct, 4)[offset(2)]           as p50_market_share,
        approx_quantiles(market_share_pct, 4)[offset(3)]           as p75_market_share,
        avg(intake_market_share)                                    as mean_intake_market_share,
        approx_quantiles(intake_market_share, 4)[offset(1)]        as p25_intake_market_share,
        approx_quantiles(intake_market_share, 4)[offset(2)]        as p50_intake_market_share,
        approx_quantiles(intake_market_share, 4)[offset(3)]        as p75_intake_market_share,
        avg(high_acuity_market_share)                               as mean_high_acuity_market_share,
        approx_quantiles(high_acuity_market_share, 4)[offset(1)]   as p25_high_acuity_market_share,
        approx_quantiles(high_acuity_market_share, 4)[offset(2)]   as p50_high_acuity_market_share,
        approx_quantiles(high_acuity_market_share, 4)[offset(3)]   as p75_high_acuity_market_share,
        avg(ongoing_market_share)                                   as mean_ongoing_market_share,
        approx_quantiles(ongoing_market_share, 4)[offset(1)]       as p25_ongoing_market_share,
        approx_quantiles(ongoing_market_share, 4)[offset(2)]       as p50_ongoing_market_share,
        approx_quantiles(ongoing_market_share, 4)[offset(3)]       as p75_ongoing_market_share,
        avg(intake_revenue_pct)                                     as mean_intake_revenue_pct,
        approx_quantiles(intake_revenue_pct, 4)[offset(1)]         as p25_intake_revenue_pct,
        approx_quantiles(intake_revenue_pct, 4)[offset(2)]         as p50_intake_revenue_pct,
        approx_quantiles(intake_revenue_pct, 4)[offset(3)]         as p75_intake_revenue_pct,
        avg(high_acuity_revenue_pct)                                as mean_high_acuity_revenue_pct,
        approx_quantiles(high_acuity_revenue_pct, 4)[offset(1)]    as p25_high_acuity_revenue_pct,
        approx_quantiles(high_acuity_revenue_pct, 4)[offset(2)]    as p50_high_acuity_revenue_pct,
        approx_quantiles(high_acuity_revenue_pct, 4)[offset(3)]    as p75_high_acuity_revenue_pct,
        avg(ongoing_revenue_pct)                                    as mean_ongoing_revenue_pct,
        approx_quantiles(ongoing_revenue_pct, 4)[offset(1)]        as p25_ongoing_revenue_pct,
        approx_quantiles(ongoing_revenue_pct, 4)[offset(2)]        as p50_ongoing_revenue_pct,
        approx_quantiles(ongoing_revenue_pct, 4)[offset(3)]        as p75_ongoing_revenue_pct,
        avg(intake_bene_pct)                                        as mean_intake_bene_pct,
        approx_quantiles(intake_bene_pct, 4)[offset(1)]            as p25_intake_bene_pct,
        approx_quantiles(intake_bene_pct, 4)[offset(2)]            as p50_intake_bene_pct,
        approx_quantiles(intake_bene_pct, 4)[offset(3)]            as p75_intake_bene_pct,
        avg(high_acuity_bene_pct)                                   as mean_high_acuity_bene_pct,
        approx_quantiles(high_acuity_bene_pct, 4)[offset(1)]       as p25_high_acuity_bene_pct,
        approx_quantiles(high_acuity_bene_pct, 4)[offset(2)]       as p50_high_acuity_bene_pct,
        approx_quantiles(high_acuity_bene_pct, 4)[offset(3)]       as p75_high_acuity_bene_pct,
        avg(ongoing_bene_pct)                                       as mean_ongoing_bene_pct,
        approx_quantiles(ongoing_bene_pct, 4)[offset(1)]           as p25_ongoing_bene_pct,
        approx_quantiles(ongoing_bene_pct, 4)[offset(2)]           as p50_ongoing_bene_pct,
        approx_quantiles(ongoing_bene_pct, 4)[offset(3)]           as p75_ongoing_bene_pct
    from base where org_zip5 != ''
    group by org_type, peer_group, size_band, market_tier, geo_level, geo_id, period_year
    having count(distinct org_slug) >= 3
),

-- ── type_size_market — tightest cut ──────────────────────────────────────────

tsm_national as (
    select org_type, 'type_size_market' as peer_group,
        size_band, market_tier,
        'national' as geo_level, 'US' as geo_id, period_year,
        count(distinct org_slug)                              as n,
        avg(panel_per_clinician)                                   as mean_panel_per_clin,
        approx_quantiles(panel_per_clinician, 4)[offset(1)]       as p25_panel_per_clin,
        approx_quantiles(panel_per_clinician, 4)[offset(2)]       as p50_panel_per_clin,
        approx_quantiles(panel_per_clinician, 4)[offset(3)]       as p75_panel_per_clin,
        stddev(panel_per_clinician)                                as std_panel_per_clin,
        avg(cast(servicing_npi_count as float64))                  as mean_clinician_count,
        approx_quantiles(servicing_npi_count, 4)[offset(1)]       as p25_clinician_count,
        approx_quantiles(servicing_npi_count, 4)[offset(2)]       as p50_clinician_count,
        approx_quantiles(servicing_npi_count, 4)[offset(3)]       as p75_clinician_count,
        avg(claims_per_beneficiary)                                as mean_claims_per_bene,
        approx_quantiles(claims_per_beneficiary, 4)[offset(1)]    as p25_claims_per_bene,
        approx_quantiles(claims_per_beneficiary, 4)[offset(2)]    as p50_claims_per_bene,
        approx_quantiles(claims_per_beneficiary, 4)[offset(3)]    as p75_claims_per_bene,
        stddev(claims_per_beneficiary)                             as std_claims_per_bene,
        avg(payment_per_claim)                                     as mean_payment_per_claim,
        approx_quantiles(payment_per_claim, 4)[offset(1)]         as p25_payment_per_claim,
        approx_quantiles(payment_per_claim, 4)[offset(2)]         as p50_payment_per_claim,
        approx_quantiles(payment_per_claim, 4)[offset(3)]         as p75_payment_per_claim,
        stddev(payment_per_claim)                                  as std_payment_per_claim,
        avg(psychiatry_pct)    as avg_psychiatry_pct,
        avg(counselor_pct)     as avg_counselor_pct,
        avg(social_worker_pct) as avg_social_worker_pct,
        avg(mft_pct)           as avg_mft_pct,
        avg(psychologist_pct)  as avg_psychologist_pct,
        avg(aprn_pct)          as avg_aprn_pct,
        avg(market_share_pct)                                      as mean_market_share,
        approx_quantiles(market_share_pct, 4)[offset(1)]           as p25_market_share,
        approx_quantiles(market_share_pct, 4)[offset(2)]           as p50_market_share,
        approx_quantiles(market_share_pct, 4)[offset(3)]           as p75_market_share,
        avg(intake_market_share)                                    as mean_intake_market_share,
        approx_quantiles(intake_market_share, 4)[offset(1)]        as p25_intake_market_share,
        approx_quantiles(intake_market_share, 4)[offset(2)]        as p50_intake_market_share,
        approx_quantiles(intake_market_share, 4)[offset(3)]        as p75_intake_market_share,
        avg(high_acuity_market_share)                               as mean_high_acuity_market_share,
        approx_quantiles(high_acuity_market_share, 4)[offset(1)]   as p25_high_acuity_market_share,
        approx_quantiles(high_acuity_market_share, 4)[offset(2)]   as p50_high_acuity_market_share,
        approx_quantiles(high_acuity_market_share, 4)[offset(3)]   as p75_high_acuity_market_share,
        avg(ongoing_market_share)                                   as mean_ongoing_market_share,
        approx_quantiles(ongoing_market_share, 4)[offset(1)]       as p25_ongoing_market_share,
        approx_quantiles(ongoing_market_share, 4)[offset(2)]       as p50_ongoing_market_share,
        approx_quantiles(ongoing_market_share, 4)[offset(3)]       as p75_ongoing_market_share,
        avg(intake_revenue_pct)                                     as mean_intake_revenue_pct,
        approx_quantiles(intake_revenue_pct, 4)[offset(1)]         as p25_intake_revenue_pct,
        approx_quantiles(intake_revenue_pct, 4)[offset(2)]         as p50_intake_revenue_pct,
        approx_quantiles(intake_revenue_pct, 4)[offset(3)]         as p75_intake_revenue_pct,
        avg(high_acuity_revenue_pct)                                as mean_high_acuity_revenue_pct,
        approx_quantiles(high_acuity_revenue_pct, 4)[offset(1)]    as p25_high_acuity_revenue_pct,
        approx_quantiles(high_acuity_revenue_pct, 4)[offset(2)]    as p50_high_acuity_revenue_pct,
        approx_quantiles(high_acuity_revenue_pct, 4)[offset(3)]    as p75_high_acuity_revenue_pct,
        avg(ongoing_revenue_pct)                                    as mean_ongoing_revenue_pct,
        approx_quantiles(ongoing_revenue_pct, 4)[offset(1)]        as p25_ongoing_revenue_pct,
        approx_quantiles(ongoing_revenue_pct, 4)[offset(2)]        as p50_ongoing_revenue_pct,
        approx_quantiles(ongoing_revenue_pct, 4)[offset(3)]        as p75_ongoing_revenue_pct,
        avg(intake_bene_pct)                                        as mean_intake_bene_pct,
        approx_quantiles(intake_bene_pct, 4)[offset(1)]            as p25_intake_bene_pct,
        approx_quantiles(intake_bene_pct, 4)[offset(2)]            as p50_intake_bene_pct,
        approx_quantiles(intake_bene_pct, 4)[offset(3)]            as p75_intake_bene_pct,
        avg(high_acuity_bene_pct)                                   as mean_high_acuity_bene_pct,
        approx_quantiles(high_acuity_bene_pct, 4)[offset(1)]       as p25_high_acuity_bene_pct,
        approx_quantiles(high_acuity_bene_pct, 4)[offset(2)]       as p50_high_acuity_bene_pct,
        approx_quantiles(high_acuity_bene_pct, 4)[offset(3)]       as p75_high_acuity_bene_pct,
        avg(ongoing_bene_pct)                                       as mean_ongoing_bene_pct,
        approx_quantiles(ongoing_bene_pct, 4)[offset(1)]           as p25_ongoing_bene_pct,
        approx_quantiles(ongoing_bene_pct, 4)[offset(2)]           as p50_ongoing_bene_pct,
        approx_quantiles(ongoing_bene_pct, 4)[offset(3)]           as p75_ongoing_bene_pct
    from base
    group by org_type, peer_group, size_band, market_tier, geo_level, geo_id, period_year
    having count(distinct org_slug) >= 3
),

tsm_state as (
    select org_type, 'type_size_market' as peer_group,
        size_band, market_tier,
        'state' as geo_level, org_state as geo_id, period_year,
        count(distinct org_slug)                              as n,
        avg(panel_per_clinician)                                   as mean_panel_per_clin,
        approx_quantiles(panel_per_clinician, 4)[offset(1)]       as p25_panel_per_clin,
        approx_quantiles(panel_per_clinician, 4)[offset(2)]       as p50_panel_per_clin,
        approx_quantiles(panel_per_clinician, 4)[offset(3)]       as p75_panel_per_clin,
        stddev(panel_per_clinician)                                as std_panel_per_clin,
        avg(cast(servicing_npi_count as float64))                  as mean_clinician_count,
        approx_quantiles(servicing_npi_count, 4)[offset(1)]       as p25_clinician_count,
        approx_quantiles(servicing_npi_count, 4)[offset(2)]       as p50_clinician_count,
        approx_quantiles(servicing_npi_count, 4)[offset(3)]       as p75_clinician_count,
        avg(claims_per_beneficiary)                                as mean_claims_per_bene,
        approx_quantiles(claims_per_beneficiary, 4)[offset(1)]    as p25_claims_per_bene,
        approx_quantiles(claims_per_beneficiary, 4)[offset(2)]    as p50_claims_per_bene,
        approx_quantiles(claims_per_beneficiary, 4)[offset(3)]    as p75_claims_per_bene,
        stddev(claims_per_beneficiary)                             as std_claims_per_bene,
        avg(payment_per_claim)                                     as mean_payment_per_claim,
        approx_quantiles(payment_per_claim, 4)[offset(1)]         as p25_payment_per_claim,
        approx_quantiles(payment_per_claim, 4)[offset(2)]         as p50_payment_per_claim,
        approx_quantiles(payment_per_claim, 4)[offset(3)]         as p75_payment_per_claim,
        stddev(payment_per_claim)                                  as std_payment_per_claim,
        avg(psychiatry_pct)    as avg_psychiatry_pct,
        avg(counselor_pct)     as avg_counselor_pct,
        avg(social_worker_pct) as avg_social_worker_pct,
        avg(mft_pct)           as avg_mft_pct,
        avg(psychologist_pct)  as avg_psychologist_pct,
        avg(aprn_pct)          as avg_aprn_pct,
        avg(market_share_pct)                                      as mean_market_share,
        approx_quantiles(market_share_pct, 4)[offset(1)]           as p25_market_share,
        approx_quantiles(market_share_pct, 4)[offset(2)]           as p50_market_share,
        approx_quantiles(market_share_pct, 4)[offset(3)]           as p75_market_share,
        avg(intake_market_share)                                    as mean_intake_market_share,
        approx_quantiles(intake_market_share, 4)[offset(1)]        as p25_intake_market_share,
        approx_quantiles(intake_market_share, 4)[offset(2)]        as p50_intake_market_share,
        approx_quantiles(intake_market_share, 4)[offset(3)]        as p75_intake_market_share,
        avg(high_acuity_market_share)                               as mean_high_acuity_market_share,
        approx_quantiles(high_acuity_market_share, 4)[offset(1)]   as p25_high_acuity_market_share,
        approx_quantiles(high_acuity_market_share, 4)[offset(2)]   as p50_high_acuity_market_share,
        approx_quantiles(high_acuity_market_share, 4)[offset(3)]   as p75_high_acuity_market_share,
        avg(ongoing_market_share)                                   as mean_ongoing_market_share,
        approx_quantiles(ongoing_market_share, 4)[offset(1)]       as p25_ongoing_market_share,
        approx_quantiles(ongoing_market_share, 4)[offset(2)]       as p50_ongoing_market_share,
        approx_quantiles(ongoing_market_share, 4)[offset(3)]       as p75_ongoing_market_share,
        avg(intake_revenue_pct)                                     as mean_intake_revenue_pct,
        approx_quantiles(intake_revenue_pct, 4)[offset(1)]         as p25_intake_revenue_pct,
        approx_quantiles(intake_revenue_pct, 4)[offset(2)]         as p50_intake_revenue_pct,
        approx_quantiles(intake_revenue_pct, 4)[offset(3)]         as p75_intake_revenue_pct,
        avg(high_acuity_revenue_pct)                                as mean_high_acuity_revenue_pct,
        approx_quantiles(high_acuity_revenue_pct, 4)[offset(1)]    as p25_high_acuity_revenue_pct,
        approx_quantiles(high_acuity_revenue_pct, 4)[offset(2)]    as p50_high_acuity_revenue_pct,
        approx_quantiles(high_acuity_revenue_pct, 4)[offset(3)]    as p75_high_acuity_revenue_pct,
        avg(ongoing_revenue_pct)                                    as mean_ongoing_revenue_pct,
        approx_quantiles(ongoing_revenue_pct, 4)[offset(1)]        as p25_ongoing_revenue_pct,
        approx_quantiles(ongoing_revenue_pct, 4)[offset(2)]        as p50_ongoing_revenue_pct,
        approx_quantiles(ongoing_revenue_pct, 4)[offset(3)]        as p75_ongoing_revenue_pct,
        avg(intake_bene_pct)                                        as mean_intake_bene_pct,
        approx_quantiles(intake_bene_pct, 4)[offset(1)]            as p25_intake_bene_pct,
        approx_quantiles(intake_bene_pct, 4)[offset(2)]            as p50_intake_bene_pct,
        approx_quantiles(intake_bene_pct, 4)[offset(3)]            as p75_intake_bene_pct,
        avg(high_acuity_bene_pct)                                   as mean_high_acuity_bene_pct,
        approx_quantiles(high_acuity_bene_pct, 4)[offset(1)]       as p25_high_acuity_bene_pct,
        approx_quantiles(high_acuity_bene_pct, 4)[offset(2)]       as p50_high_acuity_bene_pct,
        approx_quantiles(high_acuity_bene_pct, 4)[offset(3)]       as p75_high_acuity_bene_pct,
        avg(ongoing_bene_pct)                                       as mean_ongoing_bene_pct,
        approx_quantiles(ongoing_bene_pct, 4)[offset(1)]           as p25_ongoing_bene_pct,
        approx_quantiles(ongoing_bene_pct, 4)[offset(2)]           as p50_ongoing_bene_pct,
        approx_quantiles(ongoing_bene_pct, 4)[offset(3)]           as p75_ongoing_bene_pct
    from base where org_state != ''
    group by org_type, peer_group, size_band, market_tier, geo_level, geo_id, period_year
    having count(distinct org_slug) >= 3
),

tsm_zip as (
    select org_type, 'type_size_market' as peer_group,
        size_band, market_tier,
        'zip' as geo_level, org_zip5 as geo_id, period_year,
        count(distinct org_slug)                              as n,
        avg(panel_per_clinician)                                   as mean_panel_per_clin,
        approx_quantiles(panel_per_clinician, 4)[offset(1)]       as p25_panel_per_clin,
        approx_quantiles(panel_per_clinician, 4)[offset(2)]       as p50_panel_per_clin,
        approx_quantiles(panel_per_clinician, 4)[offset(3)]       as p75_panel_per_clin,
        stddev(panel_per_clinician)                                as std_panel_per_clin,
        avg(cast(servicing_npi_count as float64))                  as mean_clinician_count,
        approx_quantiles(servicing_npi_count, 4)[offset(1)]       as p25_clinician_count,
        approx_quantiles(servicing_npi_count, 4)[offset(2)]       as p50_clinician_count,
        approx_quantiles(servicing_npi_count, 4)[offset(3)]       as p75_clinician_count,
        avg(claims_per_beneficiary)                                as mean_claims_per_bene,
        approx_quantiles(claims_per_beneficiary, 4)[offset(1)]    as p25_claims_per_bene,
        approx_quantiles(claims_per_beneficiary, 4)[offset(2)]    as p50_claims_per_bene,
        approx_quantiles(claims_per_beneficiary, 4)[offset(3)]    as p75_claims_per_bene,
        stddev(claims_per_beneficiary)                             as std_claims_per_bene,
        avg(payment_per_claim)                                     as mean_payment_per_claim,
        approx_quantiles(payment_per_claim, 4)[offset(1)]         as p25_payment_per_claim,
        approx_quantiles(payment_per_claim, 4)[offset(2)]         as p50_payment_per_claim,
        approx_quantiles(payment_per_claim, 4)[offset(3)]         as p75_payment_per_claim,
        stddev(payment_per_claim)                                  as std_payment_per_claim,
        avg(psychiatry_pct)    as avg_psychiatry_pct,
        avg(counselor_pct)     as avg_counselor_pct,
        avg(social_worker_pct) as avg_social_worker_pct,
        avg(mft_pct)           as avg_mft_pct,
        avg(psychologist_pct)  as avg_psychologist_pct,
        avg(aprn_pct)          as avg_aprn_pct,
        avg(market_share_pct)                                      as mean_market_share,
        approx_quantiles(market_share_pct, 4)[offset(1)]           as p25_market_share,
        approx_quantiles(market_share_pct, 4)[offset(2)]           as p50_market_share,
        approx_quantiles(market_share_pct, 4)[offset(3)]           as p75_market_share,
        avg(intake_market_share)                                    as mean_intake_market_share,
        approx_quantiles(intake_market_share, 4)[offset(1)]        as p25_intake_market_share,
        approx_quantiles(intake_market_share, 4)[offset(2)]        as p50_intake_market_share,
        approx_quantiles(intake_market_share, 4)[offset(3)]        as p75_intake_market_share,
        avg(high_acuity_market_share)                               as mean_high_acuity_market_share,
        approx_quantiles(high_acuity_market_share, 4)[offset(1)]   as p25_high_acuity_market_share,
        approx_quantiles(high_acuity_market_share, 4)[offset(2)]   as p50_high_acuity_market_share,
        approx_quantiles(high_acuity_market_share, 4)[offset(3)]   as p75_high_acuity_market_share,
        avg(ongoing_market_share)                                   as mean_ongoing_market_share,
        approx_quantiles(ongoing_market_share, 4)[offset(1)]       as p25_ongoing_market_share,
        approx_quantiles(ongoing_market_share, 4)[offset(2)]       as p50_ongoing_market_share,
        approx_quantiles(ongoing_market_share, 4)[offset(3)]       as p75_ongoing_market_share,
        avg(intake_revenue_pct)                                     as mean_intake_revenue_pct,
        approx_quantiles(intake_revenue_pct, 4)[offset(1)]         as p25_intake_revenue_pct,
        approx_quantiles(intake_revenue_pct, 4)[offset(2)]         as p50_intake_revenue_pct,
        approx_quantiles(intake_revenue_pct, 4)[offset(3)]         as p75_intake_revenue_pct,
        avg(high_acuity_revenue_pct)                                as mean_high_acuity_revenue_pct,
        approx_quantiles(high_acuity_revenue_pct, 4)[offset(1)]    as p25_high_acuity_revenue_pct,
        approx_quantiles(high_acuity_revenue_pct, 4)[offset(2)]    as p50_high_acuity_revenue_pct,
        approx_quantiles(high_acuity_revenue_pct, 4)[offset(3)]    as p75_high_acuity_revenue_pct,
        avg(ongoing_revenue_pct)                                    as mean_ongoing_revenue_pct,
        approx_quantiles(ongoing_revenue_pct, 4)[offset(1)]        as p25_ongoing_revenue_pct,
        approx_quantiles(ongoing_revenue_pct, 4)[offset(2)]        as p50_ongoing_revenue_pct,
        approx_quantiles(ongoing_revenue_pct, 4)[offset(3)]        as p75_ongoing_revenue_pct,
        avg(intake_bene_pct)                                        as mean_intake_bene_pct,
        approx_quantiles(intake_bene_pct, 4)[offset(1)]            as p25_intake_bene_pct,
        approx_quantiles(intake_bene_pct, 4)[offset(2)]            as p50_intake_bene_pct,
        approx_quantiles(intake_bene_pct, 4)[offset(3)]            as p75_intake_bene_pct,
        avg(high_acuity_bene_pct)                                   as mean_high_acuity_bene_pct,
        approx_quantiles(high_acuity_bene_pct, 4)[offset(1)]       as p25_high_acuity_bene_pct,
        approx_quantiles(high_acuity_bene_pct, 4)[offset(2)]       as p50_high_acuity_bene_pct,
        approx_quantiles(high_acuity_bene_pct, 4)[offset(3)]       as p75_high_acuity_bene_pct,
        avg(ongoing_bene_pct)                                       as mean_ongoing_bene_pct,
        approx_quantiles(ongoing_bene_pct, 4)[offset(1)]           as p25_ongoing_bene_pct,
        approx_quantiles(ongoing_bene_pct, 4)[offset(2)]           as p50_ongoing_bene_pct,
        approx_quantiles(ongoing_bene_pct, 4)[offset(3)]           as p75_ongoing_bene_pct
    from base where org_zip5 != ''
    group by org_type, peer_group, size_band, market_tier, geo_level, geo_id, period_year
    having count(distinct org_slug) >= 3
)

select * from to_national union all
select * from to_state    union all
select * from to_zip      union all
select * from ts_national union all
select * from ts_state    union all
select * from ts_zip      union all
select * from tm_national union all
select * from tm_state    union all
select * from tm_zip      union all
select * from tsm_national union all
select * from tsm_state    union all
select * from tsm_zip
